version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-deps:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-deps:
        patterns:
          - "*"
